### ISSUE TITLE
Håndtere retning på referanser for opprettelse av ny flate

### ISSUE THREAD

**Issue by atlefren** [kartverket/NGIS-OpenAPI-felleskomponent-delt-geometri#10]
![image](https://user-images.githubusercontent.com/1829927/186144543-85bfeb64-6708-4b8c-a963-07c26abac456.png)

Gitt at du skal lage en flate ved å kombinere linje 1, 2 og 3 i figuren over. 

Da ønsker vi å: 

1. Sende inn linje 1, 2 og 3 med id og geometri
2. Få ut et polygon (angitt i svart), og en liste mer IDer, der id3 har et minustegn siden den er snudd

Vi må altså finne igjen linje-idene i den oppretta flata og sørge for å angi retning

**Comment by rosand** [comment]
En liten kommentar.
Flaten skal beskrives "mot klokken" rundt polygonet, så beskrivelsen skal være: -1, 3, -2

**Comment by larseggan** [comment]
Enig, mot klokken for ytre ring, med klokken for første hull etc.
