### ISSUE TITLE
Delt geometri: Håndtere opprettelse av punkt på delt linje

### ISSUE THREAD

**Issue by andreasbaa** [kartverket/NGIS-OpenAPI-felleskomponent-delt-geometri#46]
Brukeren oppretter et nytt punkt på en delt avgrensingslinje og får returnert 2 nye flater ink. refererte linjer

**Comment by atlefren** [comment]
![image](https://user-images.githubusercontent.com/1829927/193812265-8a602743-f096-4636-a092-5bb49936e4d9.png)
