### ISSUE TITLE
Delt geometri: Håndtere flytting av punkt på delt linje

### ISSUE THREAD

**Issue by andreasbaa** [kartverket/NGIS-OpenAPI-felleskomponent-delt-geometri#47]
Brukeren flytter et punkt på en delt avgrensingslinje og får returnert 2 nye flater ink. refererte linjer​

**Comment by atlefren** [comment]
![image](https://user-images.githubusercontent.com/1829927/193812535-878f4fe6-4962-40bc-8d04-0b805bb78e6b.png)
